#!/usr/bin/env python3
"""
Format citations from immcantation_citations.tsv into an rst file for readthedocs.

Usage:
python format_citations.py -i immcantation_citations.tsv -c immcantation-publications.tsv -o ../citedby.rst

"""

import pandas as pd
import sys
import argparse
from pathlib import Path
from datetime import datetime

def create_rst_output(df, output_file, download_date, core_publications_file, include_doi=False):
    """Create an RST file with formatted citations and clickable PubMed ID links.
    
    Args:
        df: DataFrame with citations
        output_file: Path to output RST file
        download_date: Date string for last update
        core_publications_file: Path to core publications TSV
        include_doi: Whether to include DOI links (default: False)
    """
    total_citations = len(df)
    
    # Read core publications
    core_pubs = []
    if core_publications_file.exists():
        core_df = pd.read_csv(core_publications_file, sep="\t", dtype=str)
        for _, row in core_df.iterrows():
            core_pubs.append({
                'pmid': row.get('PMID', ''),
                'title': row.get('title', ''),
                'doi': row.get('doi', ''),
                'published': row.get('published', '')
            })
    
    with open(output_file, 'w', encoding='utf-8') as f:
        # Add warning comment for contributors
        f.write(".. DO NOT EDIT THIS FILE DIRECTLY\n")
        f.write("   This file is automatically generated by docs/_citations/format_citations.py\n")
        
        f.write(".. _citedby:\n\n")
        f.write("Cited by\n")
        f.write("========\n\n")
        
        # Citation count badge
        f.write(f".. image:: https://img.shields.io/badge/Cited%20by-{total_citations}-blue\n")
        f.write("   :alt: Total Citing Papers\n\n")
        
        f.write("This page lists scientific publications that have cited `core publications`_ of the \n")
        f.write("Immcantation framework in their research. Citations are collected from PubMed \n")
        f.write("and updated regularly. Citing papers are counted only once, even if they cite \n")
        f.write("multiple Immcantation core publications.\n\n")
        f.write(f"**Total papers:** {total_citations} | **Last updated:** {download_date}\n\n")
        
        for idx, row in df.iterrows():
            # Extract fields
            title = row.get('title', '').strip() if pd.notna(row.get('title')) else 'No title'
            citing_pmid = row.get('citing_pmid', '').strip() if pd.notna(row.get('citing_pmid')) else ''
            authors = row.get('authors', '').strip() if pd.notna(row.get('authors')) else ''
            journal = row.get('journal', '').strip() if pd.notna(row.get('journal')) else ''
            pub_date = row.get('publication_date', '').strip() if pd.notna(row.get('publication_date')) else ''
            doi = row.get('doi', '').strip() if pd.notna(row.get('doi')) else ''
            
            # Build AMA-style citation
            parts = []
            
            # Authors (first author et al.)
            if authors:
                first_author = authors.split(',')[0].strip()
                parts.append(f"{first_author} et al.")
            
            # Title (no link)
            parts.append(title)
            
            # Journal and year
            journal_year = []
            if journal:
                journal_year.append(f"*{journal}*")
            if pub_date:
                year = pub_date.split('-')[0]
                journal_year.append(year)
            if journal_year:
                parts.append(". ".join(journal_year))
            
            # Links (PMID and optionally DOI)
            links = []
            if citing_pmid:
                links.append(f"`PMID:{citing_pmid} <https://pubmed.ncbi.nlm.nih.gov/{citing_pmid}/>`_")
            if include_doi and doi:
                links.append(f"`DOI:{doi} <https://doi.org/{doi}>`_")
            if links:
                parts.append(" | ".join(links))
            
            # Remove trailing periods from all parts to avoid double periods
            parts = [p.rstrip('.') for p in parts]
            
            # Write citation with bullet
            f.write(f"- {'. '.join(parts)}\n\n")
        
        # Add core publications section at the end
        if core_pubs:
            f.write("\n\n")
            f.write(".. _core publications:\n\n")
            f.write(".. rubric:: Immcantation Publications\n\n")
            f.write("The following Immcantation core publications were used to identify citing papers:\n\n")
            
            for pub in core_pubs:
                pmid = pub['pmid']
                title = pub['title']
                doi = pub['doi']
                published = pub['published']
                
                # Extract year from published date
                year = ''
                if published:
                    year = published.split('-')[0]
                
                # Build AMA-style citation
                parts = []
                
                # Title (no link)
                parts.append(title)
                
                # Year
                if year:
                    parts.append(year)
                
                # Links (PMID and optionally DOI)
                links = []
                if pmid:
                    links.append(f"`PMID:{pmid} <https://pubmed.ncbi.nlm.nih.gov/{pmid}/>`_")
                if include_doi and doi:
                    links.append(f"`DOI <https://doi.org/{doi}>`_")
                if links:
                    parts.append(" | ".join(links))
                
                # Remove trailing periods from all parts to avoid double periods
                parts = [p.rstrip('.') for p in parts]
                
                f.write(f"- {'. '.join(parts)}\n\n")

def main():
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description="Format citations from TSV to RST with clickable PubMed ID links."
    )
    parser.add_argument(
        "-i", "--input",
        type=str,
        default=None,
        help="Input TSV file path (default: <script_dir>/immcantation_citations.tsv)"
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help="Output RST file path (default: current working directory, same name as input with .rst extension)"
    )
    parser.add_argument(
        "-c", "--core-pubs",
        type=str,
        default=None,
        help="Core publications TSV file path (default: <script_dir>/immcantation-publications.tsv)"
    )
    parser.add_argument(
        "--doi",
        action="store_true",
        help="Include DOI links in citations (default: False)"
    )
    
    args = parser.parse_args()
    
    # Define input file path
    script_dir = Path(__file__).parent
    if args.input:
        input_file = Path(args.input)
    else:
        input_file = script_dir / "immcantation_citations.tsv"
    
    # Define core publications file
    if args.core_pubs:
        core_publications_file = Path(args.core_pubs)
    else:
        core_publications_file = script_dir / "immcantation-publications.tsv"
    
    # Define output file path
    if args.output:
        output_file_rst = Path(args.output)
    else:
        # Default: current working directory, same name as input but .rst extension
        output_file_rst = Path.cwd() / (input_file.stem + ".rst")
    
    # Check if input file exists
    if not input_file.exists():
        print(f"Error: Input file {input_file} does not exist.")
        sys.exit(1)
    
    print(f"Reading data from: {input_file}")
    
    # Define the columns in the desired order
    columns = [
        "citing_pmid",
        "publication_date",
        "doi",
        "title",
        "authors",
        "corresponding_authors",
        "corresponding_emails",
        "journal",
        "abstract"
    ]
    
    try:
        # Read the TSV file
        print("Loading TSV file...")
        
        # First, try to read the download date from the comment line
        download_date = None
        with open(input_file, 'r', encoding='utf-8') as f:
            first_line = f.readline().strip()
            if first_line.startswith('# Downloaded:'):
                date_str = first_line.split('Downloaded:')[1].strip()
                # Convert YYYY-MM-DD to readable format
                try:
                    date_obj = datetime.strptime(date_str, "%Y-%m-%d")
                    download_date = date_obj.strftime("%B %d, %Y")
                except ValueError:
                    pass
        
        # Fallback to file modification date if no download date found
        if download_date is None:
            download_date = datetime.fromtimestamp(input_file.stat().st_mtime).strftime("%B %d, %Y")
            print("Warning: No download date found in file, using file modification date")
        
        # Read the TSV file, skipping comment lines
        df = pd.read_csv(input_file, sep="\t", dtype=str, comment='#')
        print(f"Original data shape: {df.shape}")
        
        # Check if all required columns exist
        missing_columns = [col for col in columns if col not in df.columns]
        if missing_columns:
            print(f"Error: Missing columns in input file: {missing_columns}")
            print(f"Available columns: {list(df.columns)}")
            sys.exit(1)
        
        # Subset the columns
        print("Selecting specified columns...")
        df_subset = df[columns].copy()
        
        # Add original_pmid column if needed for tracking
        if 'original_pmid' in df.columns:
            df_subset['original_pmid'] = df['original_pmid']
        
        # Remove duplicates based on DOI and PMID
        print("Removing duplicates based on DOI and PMID...")
        original_count = len(df_subset)
        
        # Track removed duplicates with detailed information
        removed_entries = []
        
        # First remove DOI duplicates
        # Group by DOI to find which Immcantation papers each citing paper references
        doi_groups = df_subset.groupby('doi')['original_pmid'].apply(list).to_dict()
        
        doi_duplicates = df_subset[df_subset.duplicated(subset=["doi"], keep="first")]
        for _, row in doi_duplicates.iterrows():
            doi = row.get('doi', '')
            immcantation_papers = doi_groups.get(doi, [])
            removed_entries.append({
                'title': row.get('title', ''),
                'citing_pmid': row.get('citing_pmid', ''),
                'doi': doi,
                'original_pmids': immcantation_papers,
                'count': len(immcantation_papers),
                'reason': 'Duplicate DOI'
            })
        df_deduplicated = df_subset.drop_duplicates(subset=["doi"], keep="first")
        
        # Then remove PMID duplicates
        # Group by PMID to find which Immcantation papers each citing paper references
        pmid_groups = df_deduplicated.groupby('citing_pmid')['original_pmid'].apply(list).to_dict()
        
        pmid_duplicates = df_deduplicated[df_deduplicated.duplicated(subset=["citing_pmid"], keep="first")]
        for _, row in pmid_duplicates.iterrows():
            citing_pmid = row.get('citing_pmid', '')
            immcantation_papers = pmid_groups.get(citing_pmid, [])
            removed_entries.append({
                'title': row.get('title', ''),
                'citing_pmid': citing_pmid,
                'doi': row.get('doi', ''),
                'original_pmids': immcantation_papers,
                'count': len(immcantation_papers),
                'reason': 'Duplicate PMID'
            })
        df_deduplicated = df_deduplicated.drop_duplicates(subset=["citing_pmid"], keep="first")
        
        duplicates_removed = original_count - len(df_deduplicated)
        print(f"Removed {duplicates_removed} duplicate entries")
        
        # Write log of removed entries
        if removed_entries:
            log_file = output_file_rst.parent / (output_file_rst.stem + "_removed.log")
            print(f"Writing log of removed entries to: {log_file}")
            with open(log_file, 'w', encoding='utf-8') as f:
                f.write(f"Removed Entries Log\n")
                f.write(f"{'='*80}\n")
                f.write(f"Total removed: {len(removed_entries)}\n\n")
                
                # Count multi-citation entries
                multi_citation_count = sum(1 for entry in removed_entries if entry['count'] > 1)
                if multi_citation_count > 0:
                    f.write(f"Entries citing multiple Immcantation papers: {multi_citation_count}\n\n")
                
                for entry in removed_entries:
                    f.write(f"Reason: {entry['reason']}\n")
                    f.write(f"  Title: {entry['title']}\n")
                    f.write(f"  Citing PMID: {entry['citing_pmid']}\n")
                    f.write(f"  DOI: {entry['doi']}\n")
                    
                    # Report which Immcantation papers were cited
                    if entry['count'] > 1:
                        f.write(f"  ** Cites {entry['count']} different Immcantation papers **\n")
                    f.write(f"  Immcantation papers cited (PMID): {', '.join(map(str, entry['original_pmids']))}\n")
                    f.write(f"{'-'*80}\n")
        
        # Convert publication_date to datetime for proper sorting
        print("Sorting by publication date (most recent first)...")
        df_deduplicated = df_deduplicated.copy()  # Explicit copy to avoid warning
        df_deduplicated["publication_date"] = pd.to_datetime(df_deduplicated["publication_date"], errors="coerce")
        df_sorted = df_deduplicated.sort_values(by="publication_date", ascending=False)
        
        # Convert publication_date back to string format for output
        df_sorted = df_sorted.copy()  # Explicit copy to avoid warning
        df_sorted["publication_date"] = df_sorted["publication_date"].dt.strftime("%Y-%m-%d")
        
        # Handle any NaT values that might have been created
        df_sorted["publication_date"] = df_sorted["publication_date"].fillna("")
        
        print(f"Final data shape: {df_sorted.shape}")
        
        # Create RST output
        print(f"Creating RST file: {output_file_rst}")
        print(f"Total unique citations (after deduplication): {len(df_sorted)}")
        print(f"Download date: {download_date}")
        print(f"Include DOI links: {args.doi}")
        create_rst_output(df_sorted, output_file_rst, download_date, core_publications_file, include_doi=args.doi)
        print(f"RST output saved to: {output_file_rst}")
        print("Successfully created citations.rst file!")
        
    except Exception as e:
        print(f"Error processing file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
